// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include <cpp/prime_number_generator.hpp>
#include "djinni_support.hpp"

namespace djinni_generated {

class NativePrimeNumberGenerator final : ::djinni::JniInterface<::primenumbers::PrimeNumberGenerator, NativePrimeNumberGenerator> {
public:
    using CppType = std::shared_ptr<::primenumbers::PrimeNumberGenerator>;
    using CppOptType = std::shared_ptr<::primenumbers::PrimeNumberGenerator>;
    using JniType = jobject;

    using Boxed = NativePrimeNumberGenerator;

    ~NativePrimeNumberGenerator();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativePrimeNumberGenerator>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativePrimeNumberGenerator>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativePrimeNumberGenerator();
    friend ::djinni::JniClass<NativePrimeNumberGenerator>;
    friend ::djinni::JniInterface<::primenumbers::PrimeNumberGenerator, NativePrimeNumberGenerator>;

};

}  // namespace djinni_generated
