// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#include "NativePrimeNumberGenerator.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativePrimeNumberGenerator::NativePrimeNumberGenerator() : ::djinni::JniInterface<::primenumbers::PrimeNumberGenerator, NativePrimeNumberGenerator>("com/software/primenumbers/PrimeNumberGenerator$CppProxy") {}

NativePrimeNumberGenerator::~NativePrimeNumberGenerator() = default;


CJNIEXPORT void JNICALL Java_com_software_primenumbers_PrimeNumberGenerator_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::primenumbers::PrimeNumberGenerator>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jint JNICALL Java_com_software_primenumbers_PrimeNumberGenerator_generatePrime(JNIEnv* jniEnv, jobject /*this*/, jint j_previousPrime)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::primenumbers::PrimeNumberGenerator::generate_prime(::djinni::I32::toCpp(jniEnv, j_previousPrime));
        return ::djinni::release(::djinni::I32::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
