// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import "HWPrimeNumberGenerator+Private.h"
#import "HWPrimeNumberGenerator.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface HWPrimeNumberGenerator ()

- (id)initWithCpp:(const std::shared_ptr<::primenumbers::PrimeNumberGenerator>&)cppRef;

@end

@implementation HWPrimeNumberGenerator {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::primenumbers::PrimeNumberGenerator>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::primenumbers::PrimeNumberGenerator>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (int32_t)generatePrime:(int32_t)previousPrime {
    try {
        auto objcpp_result_ = ::primenumbers::PrimeNumberGenerator::generate_prime(::djinni::I32::toCpp(previousPrime));
        return ::djinni::I32::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto PrimeNumberGenerator::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto PrimeNumberGenerator::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<HWPrimeNumberGenerator>(cpp);
}

}  // namespace djinni_generated

@end
