// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import <Foundation/Foundation.h>


@interface HWPrimeNumberGenerator : NSObject

+ (int32_t)generatePrime:(int32_t)previousPrime;

@end
