// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include <cstdint>

namespace primenumbers {

class PrimeNumberGenerator {
public:
    virtual ~PrimeNumberGenerator() {}

    static int32_t generate_prime(int32_t previousPrime);
};

}  // namespace primenumbers
